# Generated by Django 4.1.13 on 2024-03-09 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('roomates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomate',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('team_name', models.CharField(max_length=255)),
                ('user_id', models.ManyToManyField(db_column='user_id', related_name='teams', to='roomates.roomate')),
            ],
        ),
    ]
