# Generated by Django 4.1.13 on 2024-03-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomates', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomates.team'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomates.roomate'),
        ),
    ]
